[package]
name = "profile"
version = "0.0.0"
description = "TBD"
license = "MIT OR Apache-2.0"
edition = "2021"
rust-version = "1.57"

[lib]
doctest = false

[dependencies]
once_cell = "1.3.1"
cfg-if = "1"
libc = "0.2"
la-arena = { version = "0.3.0", path = "../../lib/arena" }
countme = { version = "3.0", features = ["enable"] }
jemalloc-ctl = { version = "0.4.1", package = "tikv-jemalloc-ctl", optional = true }

[target.'cfg(target_os = "linux")'.dependencies]
perf-event = "0.4"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.8", features = ["processthreadsapi", "psapi"] }

[features]
cpu_profiler = []
jemalloc = ["jemalloc-ctl"]

# Uncomment to enable for the whole crate graph
# default = [ "cpu_profiler" ]
